server:
  port: 5000

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        corsConfigurations:
          '[/**]':
             allowedOrigins:
              - 'http://localhost:7000'
              - 'http://localhost:7001'
              - 'http://sangdam.xyz'
              - 'http://www.sangdam.xyz'
              - 'http://admin.sangdam.xyz:7000'
            allowCredentials: true # 요청시 인증 정보 전송 허가
            allowedHeaders: '*'
            allowedMethods: '*'
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/v1/member/**
          filters:
            - RewritePath=/api/v1/member/?(?<path>.*),/$\{path}

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/file/**
          filters:
            - RewritePath=/api/v1/file/?(?<path>.*),/$\{path}

        - id: psychologicaltest-service
          uri: lb://psychologicaltest-service
          predicates:
            - Path=/api/v1/psychologicalTest/**
          filters:
            - RewritePath=/api/v1/psychologicalTest/(?<path>.*), /$\{path}

        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/api/v1/board/**
          filters:
            - RewritePath=/api/v1/board/(?<path>.*), /$\{path}

        - id: counseling-service
          uri: lb://counseling-service
          predicates:
            - Path=/api/v1/counseling/**
          filters:
            - RewritePath=/api/v1/counseling/(?<path>.*), /$\{path}

# 유레카 설정
eureka:
  instance:
    hostname: ${hostname}
    #preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaHost}/eureka/

# 액츄에이터 설정
management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway
