spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:7000'
              - 'http://localhost:7001'
              - 'http://sangdam.xyz'
              - 'http://www.sangdam.xyz'
              - 'http://admin.sangdam.xyz:7000'
            allowCredentials: true # 요청 시 인증 정보 전송 허가
            allowedHeaders: '*'
            allowedMethods: '*'
